github.com:
    users:
        Dilipsangapu:
            oauth_token: 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
    git_protocol: https
    user: Dilipsangapu
    oauth_token: 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
